rmdir /S /Q .gradle
rmdir /S /Q .project
rmdir /S /Q .classpath
rmdir /S /Q .settings
rmdir /S /Q .vscode
rmdir /S /Q build
rmdir /S /Q fabric\.gradle
rmdir /S /Q fabric\.settings
rmdir /S /Q fabric\.project
rmdir /S /Q fabric\.classpath
rmdir /S /Q fabric\build
rmdir /S /Q forge\.gradle
rmdir /S /Q forge\.settings
rmdir /S /Q forge\.project
rmdir /S /Q forge\.classpath
rmdir /S /Q forge\build