modstitch.platform=fabric-loom-remap

deps.minecraft=1.20.1
deps.fabric-api=0.92.9+1.20.1

modmenu_version=7.2.2
cloth_config_version=11.1.106

opac        = curse.maven:open-parties-and-claims-636608:7112739
ftb_chunks  = curse.maven:ftb-chunks-fabric-472657:6431734
ftb_library = curse.maven:ftb-library-fabric-438495:7296747
flan        = curse.maven:flan-404578:6989318
goml        = curse.maven:get-off-my-lawn-reserved-572651:4813644

rtree_version = 0.3.0
