modstitch.platform=moddevgradle

deps.minecraft=1.21.11
deps.neoforge=21.11.42

modmenu_version=17.0.0-beta.1
cloth_config_version=21.11.153

opac         = curse.maven:open-parties-and-claims-636608:7420717
ftb_chunks   = curse.maven:ftb-chunks-forge-314906:7701627
ftb_library  = curse.maven:ftb-library-forge-404465:7718926
flan         = curse.maven:flan-forge-493246:8065261
goml         =
rtree_version = 0.3.0
