modstitch.platform=moddevgradle

deps.minecraft=1.21.1
deps.neoforge=21.1.219

cloth_config_version=15.0.140

opac        = curse.maven:open-parties-and-claims-636608:5938793
ftb_chunks  = curse.maven:ftb-chunks-forge-314906:5598952
ftb_library = curse.maven:ftb-library-forge-404465:5583834
flan        = curse.maven:flan-forge-493246:5615913
goml        =
rtree_version = 0.3.0
