modstitch.platform=fabric-loom-remap

deps.minecraft=1.21.11

deps.fabric-api=0.141.4+1.21.11

modmenu_version=17.0.0-beta.1
cloth_config_version=21.11.153

opac = curse.maven:open-parties-and-claims-636608:7420726
ftb_chunks  = curse.maven:ftb-chunks-fabric-472657:7701628
ftb_library = curse.maven:ftb-library-fabric-438495:7718925
flan = curse.maven:flan-404578:8065258
goml = curse.maven:get-off-my-lawn-reserved-572651:7415961

rtree_version = 0.3.0
