modstitch.platform=fabric-loom-remap

deps.minecraft=1.21.1

deps.fabric-api=0.116.12+1.21.1

modmenu_version=11.0.3
cloth_config_version=15.0.140

opac        = curse.maven:open-parties-and-claims-636608:5938795
ftb_chunks  = curse.maven:ftb-chunks-fabric-472657:5598951
ftb_library = curse.maven:ftb-library-fabric-438495:5583833
flan        = curse.maven:flan-404578:5615912
goml        = curse.maven:get-off-my-lawn-reserved-572651:5549396

rtree_version = 0.3.0
