modstitch.platform=moddevgradle

deps.minecraft=26.1.2
deps.neoforge=26.1.2.43-beta

cloth_config_version=26.1.154
opac         = curse.maven:open-parties-and-claims-636608:8091542
ftb_chunks   = curse.maven:ftb-chunks-forge-314906:8165043
ftb_library  = curse.maven:ftb-library-forge-404465:8160272
flan         = curse.maven:flan-forge-493246:8065341
goml         =

rtree_version = 0.3.0
