modstitch.platform=fabric-loom
deps.fabric-api=0.148.0+26.1.2

deps.minecraft=26.1.2

modmenu_version=18.0.0-beta.1
cloth_config_version=26.1.154

opac         = curse.maven:open-parties-and-claims-636608:8091542
ftb_chunks   = curse.maven:ftb-chunks-fabric-472657:8165042
ftb_library  = curse.maven:ftb-library-fabric-438495:8160271
flan         = curse.maven:flan-404578:8065344
goml         = curse.maven:get-off-my-lawn-reserved-572651:8105754

rtree_version = 0.3.0
