modstitch.platform=moddevgradle-legacy

deps.minecraft=1.20.1
deps.forge=1.20.1-47.3.0

cloth_config_version=11.1.106

opac        = curse.maven:open-parties-and-claims-636608:4784626
ftb_chunks  = curse.maven:ftb-chunks-forge-314906:6431735
ftb_library = curse.maven:ftb-library-forge-404465:7296748
flan        = curse.maven:flan-forge-493246:6989323
goml        =
rtree_version = 0.3.0
